.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GEBODOC 1 "August 09, 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
\fBgebodooc\fP \- Information collector and document creator
.SH SYNOPSIS
.B gebodoc
[ <no parameters> | \fB\-c\fR <configfiles> | \fB\-h\fR | \fB\-v\fR ]
.br
.br
.B gebodoc
[ \fB\-\-configfiles\fR ] <configfiles>
.br
.B gebodoc
[ \fB\-\-help\fR ]
.br
.B gebodoc
[ \fB\-\-version\fR ]
.SH DESCRIPTION
This manual page briefly documents the
.B gebodoc
utility.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBgebodooc\fP can be used for collecting information from various sources and creating documents out of it.
Sources of information can be static files in local file system or over the internet and in several different
formats. Information can also reside in some kind of data storage such as database, version control or bug/issue
systems such as Jira and Bugzilla.
.PP
Resulting document format can be one of several textual formats: text, HTML, XML etc, and also PDF. Basically
output format depends only about used template and used document build command.
.SH OPTIONS
\fBgebodooc\fP follows the usual GNU command line syntax, with long options starting with two dashes ('-').
A summary of options is included below.
.TP
<no parameters>
Display short usage and version.
.TP
\fB\-c\fR <configfiles>
Document configuration file that uses INI syntax.
The mandatory configuring items in [document] section contain the name of the result document, the template and output format.
Optional items in [data] section can contain variable names and values, and multicolumn and multirow list data.
.TP
.B \-h, \-\-help
Basic help and summary of options.
.TP
.B \-v, \-\-version
Show version of the script.

.SH EXAMPLES
.TP
To create an example CV document in text format with basic personal information of Donald Duck:
gebodoc -c examples/example_cv1.cfg
.PP
See file CV_Donald_Duck for the result.

.TP
To create a CV in PDF format for Donald Duck:
gebodoc -c examples/example_cv_latex_to_pdf.cfg
.PP
See file CV_Donald_Duck.pdf for the result.

.SH COPYRIGHT
.PP
Copyright \(co 2014 Mika Tapojärvi <mika.tapojarvi@embelin.fi>
.PP
Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:
.PP
The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.
.PP
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.PP
.PP
You should have received a copy of the MIT License along with this program.
If not, see <http://opensource.org/licenses/MIT/>.
.SH AUTHOR
\fBgebodooc\fP was written by Mika Tapojärvi <mika.tapojarvi@embelin.fi>.
.PP
This manual page was written by Mika Tapojärvi <mika.tapojarvi@embelin.fi>,
for the Ubuntu and Debian projects (and may be used by others).
